### ISSUE TITLE
Error using set_parameter_values

### ISSUE THREAD

**Issue by vembha** [alexeyovchinnikov/SIAN-Julia#74] opened 2022-12-08 18:25 UTC
Hello,

I am trying to check the parameter identifiability of the following ODE system:
```
using SIAN, Nemo

original_ode = @ODEmodel(
    x1'(t) = lambda - beta * x1(t) * x2(t) - dT * x1(t),
    x2'(t) = (1 - fD) * beta * x1(t) * x2(t) - x5(t) * x4(t) * x2(t) - dI * x2(t),
    x3'(t) = fD * beta * x1(t) * x2(t) - dD * x3(t),
    x4'(t) = lambdaE + alphaE * x4(t) * x2(t) / (thetaE + x2(t)) - dE * x4(t),
    x5'(t) = omega * (chif - x5(t)),
    y1(t)  = r * x2(t),
    y2(t)  = x2(t) + x3(t)
)

modified_ode = SIAN.set_parameter_values(original_ode, OrderedDict(
    dI => Nemo.QQ(1, 1),
    thetaE => Nemo.QQ(1, 10),
    dE => Nemo.QQ(1, 1)
))

res = identifiability_ode(modified_ode, get_parameters(modified_ode))
```

Although the ode is getting defined without errors, unfortunately, the `set_parameter_values` function is throwing the following error:

```
ERROR: MethodError: no method matching eval_at_dict(::AbstractAlgebra.Generic.Frac{fmpq_mpoly}, ::OrderedDict{fmpq_mpoly, fmpq_mpoly})
Closest candidates are:
  eval_at_dict(::P, ::OrderedDict{P, <:RingElem}) where P<:MPolyElem at C:\Users\vembh\.julia\packages\SIAN\dy2qV\src\util.jl:158 
Stacktrace:
 [1] (::SIAN.var"#37#43"{OrderedDict{fmpq_mpoly, fmpq_mpoly}})(::Pair{fmpq_mpoly, Union{AbstractAlgebra.Generic.Frac{fmpq_mpoly}, 
fmpq_mpoly}})
   @ SIAN .\none:0
 [2] iterate
   @ .\generator.jl:47 [inlined]
 [3] OrderedDict{fmpq_mpoly, Union{AbstractAlgebra.Generic.Frac{fmpq_mpoly}, fmpq_mpoly}}(kv::Base.Generator{Dict{fmpq_mpoly, Union{AbstractAlgebra.Generic.Frac{fmpq_mpoly}, fmpq_mpoly}}, SIAN.var"#37#43"{OrderedDict{fmpq_mpoly, fmpq_mpoly}}})
   @ OrderedCollections C:\Users\vembh\.julia\packages\OrderedCollections\PRayh\src\ordered_dict.jl:27
 [4] set_parameter_values(ode::ODE{fmpq_mpoly}, param_values::OrderedDict{fmpq_mpoly, fmpq})
   @ SIAN C:\Users\vembh\.julia\packages\SIAN\dy2qV\src\ODE.jl:50
 [5] top-level scope
   @ REPL[17]:1
```

Can someone help with what is happening? When I run the `NFkB.jl` example code, this error by `set_parameter_values` doesn't come up.

**Comment by iliailmer** [comment] 2022-12-14 17:39
@vembha Hi, I'm taking a look at that, will let you know soon.

**Comment by pogudingleb** [comment] 2023-02-12 08:14
@vembha  I believe that the issue is fixed now (in the GitHub version, can be installed by `Pkg.add(url="https://github.com/alexeyovchinnikov/SIAN-Julia")`).
@iliailmer Shall we make a release for this bug fix?

**Closed by pogudingleb** 2023-02-12 08:14 UTC
